In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'C:\Users\User\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.


In [2]:
import numpy as np

1. Create a null vector of size 10

In [3]:
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


2. How to get the documentation of the numpy add function from the command line ?

In [ ]:
python -c "import numpy; numpy.info(numpy.add)"

3. Create a null vector of size 10 but the fifth value which is 1

In [4]:
Z= np.zeros(10)
Z[4]= 1
print (Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


4. Create a vector with values ranging from 10 to 49

In [5]:
Z=np.arange(10,50)
print (Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


5.Reverse a vector (first element becomes last)

In [6]:
Z = np.arange(10,50)
Z= Z[::-1]
print (Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


6. Create a 3x3 matrix with values ranging from 0 to 8

In [7]:
Z = np.arange(9).reshape(3,3)
print (Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


7.Find indices of non-zero elements from [1,2,0,0,4,0]

In [8]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


8.Create a 3x3 identity matrix

In [9]:
Z= np.eye(3)
print (Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


8.Create a 3x3x3 array with random values

In [10]:
Z = np.random.uniform((3,3,3))
print (Z)

[1.38560599 2.72010719 2.97934265]


9.Create a 10x10 array with random values and find the minimum and maximum values

In [11]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.0004214243158934261 0.9795770986136751


10.Create a random vector of size 30 and find the mean value